- name: Combine Docker daemon environment variable configuration
  ansible.builtin.set_fact:
    _docker_service_envs: "{{ _docker_service_envs | combine(_docker_service_opts) | combine(docker_daemon_envs) }}"
  vars:
    _docker_service_opts:
      DOCKER_OPTS: "{{ docker_daemon_opts }}"

- name: Setup Docker environment file in directory {{ docker_envs_dir[_docker_os_dist_file_varity] }}
  become: true
  ansible.builtin.template:
    src: docker-envs.j2
    dest: "{{ docker_envs_dir[_docker_os_dist_file_varity] }}/docker"
    owner: root
    group: root
    mode: 0644
  register: _docker_non_systemd_envs
  vars:
    docker_envs: "{{ _docker_service_envs }}"

- name: Docker daemon restart is required
  when: _docker_non_systemd_envs is changed
  ansible.builtin.set_fact:
    _docker_restart_required: true
