- name: Combine all systemd service configuration options
  ansible.builtin.set_fact:
    _systemd_service_config: "{{ _docker_systemd_service_config_tweaks + docker_systemd_service_config }}"

- name: Ensure /etc/systemd/system/docker.service.d directory exists
  become: true
  ansible.builtin.file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: 0755

- name: Setup default Docker drop-in to enable use of environment file
  become: true
  ansible.builtin.template:
    src: drop-ins/default.conf.j2
    dest: /etc/systemd/system/docker.service.d/default.conf
    owner: root
    group: root
    mode: 0644
  register: _docker_systemd_docker_dropin
  vars:
    systemd_envs_dir: "{{ docker_envs_dir[_docker_os_dist_file_varity] }}"
    systemd_service_conf: "{{ _systemd_service_config }}"

- name: Combine Docker daemon environment variable configuration
  ansible.builtin.set_fact:
    _docker_service_envs: "{{ _docker_service_envs | combine(_docker_service_opts) | combine(docker_daemon_envs) }}"
  vars:
    _docker_service_opts:
      DOCKER_OPTS: "{{ docker_daemon_opts }}"

- name: Setup Docker environment file in directory {{ docker_envs_dir[_docker_os_dist_file_varity] }}
  become: true
  ansible.builtin.template:
    src: docker-envs.j2
    dest: "{{ docker_envs_dir[_docker_os_dist_file_varity] }}/docker-envs"
    owner: root
    group: root
    mode: 0644
  register: _docker_systemd_envs
  vars:
    docker_envs: "{{ _docker_service_envs }}"

- name: Force daemon reload of systemd
  when: _docker_systemd_docker_dropin is changed
  become: true
  ansible.builtin.systemd:
    daemon_reload: yes
  tags:
    - skip_ansible_lint

- name: Docker daemon restart is required
  when: (_docker_systemd_docker_dropin is changed) or (_docker_systemd_envs is changed)
  ansible.builtin.set_fact:
    _docker_restart_required: true
