---
# handlers file for ansible-role-docker-ce

- name: restart docker
  become: yes
  ansible.builtin.service:
    use: "{{ docker_x_service_mgr }}"
    name: docker
    state: restarted
  tags: ["install", "configure"]

- name: reload docker
  become: yes
  ansible.builtin.service:
    use: "{{ docker_x_service_mgr }}"
    name: docker
    state: reloaded
  tags: ["install", "configure"]

# Workaround because systemd cannot be used: https://github.com/ansible/ansible/issues/22171
- name: restart auditd
  become: yes
  ansible.builtin.command: service auditd restart
  tags: ["install", "configure"]
