---
# handlers file for ansible-role-docker-ce

- name: restart docker
  service:
    name: docker
    state: restarted
  become: yes
  tags: ["install", "configure"]

# Workaround because systemd cannot be used: https://github.com/ansible/ansible/issues/22171
- name: restart auditd
  shell: service auditd restart
  args:
    warn: no
  become: yes
  tags: ["install", "configure"]
