- name: Ensure lvm2 is installed
  become: true
  ansible.builtin.package:
    name: lvm2
    state: present
  register: _pkg_result
  until: _pkg_result is succeeded

- name: Create LVM volume group
  when: pool.physical_volumes|default(None)
  become: true
  community.general.lvg:
    pvs: '{{ pool.physical_volumes }}'
    state: present
    vg: '{{ pool.volume_group }}'

- name: Check if data volume exists
  become: true
  ansible.builtin.stat:
    path: '/dev/mapper/{{ pool.volume_group }}-{{ pool.name }}'
  ignore_errors: true
  register: _volume

- name: Create data volume
  when: not _volume.stat.exists
  become: true
  community.general.lvol:
    lv: '{{ pool.name }}'
    size: '{{ pool.data_size }}'
    vg: '{{ pool.volume_group }}'
  register: _datavolume_created

- name: Create meta data volume
  when: _datavolume_created is changed
  become: true
  community.general.lvol:
    lv: '{{ pool.name }}meta'
    size: '{{ pool.metadata_size }}'
    vg: '{{ pool.volume_group }}'
  tags:
    - skip_ansible_lint

- name: Convert data volume to thinpool
  when: _datavolume_created is changed
  become: true
  ansible.builtin.shell:
    lvconvert
        -y
        --zero n
        -c 512K
        --thinpool "{{ pool.volume_group }}/{{ pool.name }}"
        --poolmetadata "{{ pool.volume_group }}/{{ pool.name }}meta"
  tags:
    - skip_ansible_lint